services:
  # The PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: christmas-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - christmas-network

  # The Web Server
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8051}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - christmas-network

networks:
  christmas-network:
    driver: bridge